# Generated by Django 5.2.4 on 2025-07-25 00:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Direccion',
            fields=[
                ('direccionId', models.AutoField(primary_key=True, serialize=False)),
                ('pais', models.CharField(blank=True, max_length=50, null=True)),
                ('ubicacion', models.CharField(blank=True, max_length=50, null=True)),
                ('codigoPostal', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tarjeta',
            fields=[
                ('tarjetaID', models.AutoField(primary_key=True, serialize=False)),
                ('numeroTarjeta', models.BigIntegerField()),
                ('tipo', models.CharField(choices=[('VISA', 'VISA'), ('MASTERCARD', 'MASTERCARD'), ('DINERS', 'DINERS')], max_length=50)),
                ('titular', models.CharField(max_length=50)),
                ('CVV', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('clienteId', models.AutoField(primary_key=True, serialize=False)),
                ('nickname', models.CharField(max_length=50, unique=True)),
                ('email', models.EmailField(max_length=50)),
                ('nombre', models.CharField(max_length=50)),
                ('telefono', models.IntegerField()),
                ('direccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cliente.direccion')),
                ('tarjeta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cliente.tarjeta')),
            ],
        ),
    ]
